export const SET_INIT_SHOWS = 'SET_INIT_SHOWS';
export const SET_SINGLE_SHOW = 'SET_SINGLE_SHOW';

export const SET_SEARCHED_SHOWS = 'SET_SEARCHED_SHOWS';
export const SET_SEARCHED_SHOW_ID = 'SET_SEARCHED_SHOW_ID';